adventure_works:
  outputs:
    dbt_aw_2022:
      dataset: humanresources
      fixed_retries: 1
      keyfile: /home/pedro/.dbt/big-query-poggers-8d428dd1d855.json
      location: us
      method: service-account
      priority: interactive
      project: big-query-poggers
      threads: 1
      timeout_seconds: 300
      type: bigquery
  target: dbt_aw_2022
