version: 2

sources:
  - name: raw_normalized_adventureworks
    tables:
      - name: normalized_department
      - name: normalized_employee
      - name: normalized_employeedepartmenthistory
      - name: normalized_employeepayhistory
      - name: normalized_shift
