version: 2

sources:
  - name: humanresources
    tables:
      - name: humanresources_department
      - name: shift
      - name: jobcandidate
      - name: employeepayhistory
      - name: employeedepartmenthistory
      - name: employee
      - name: department

